whatisyourdadsage =input("what is your dads age: ")
print("whatisyourdadsage")
whatisyourmomsage =input("what is your moms age: ")
print("whatisyourmomsage")
howmanyyearsyourdadwillbeafter5year =input("howmanyyearsyourdadwillbeafter5year: ")
print("howmanyyearsyourdadwillbeafter5year")
howmanyyearsyourmomwillbeafter5years =input("howmanyyearsyormomwillbeafter5year")
print("howmanyyearsyourmomwillbeafter5years")
print("my dad will be 42 years after 5 year")
print("my mom will be 40 years after 5 yers")